# Generated by Django 4.2.16 on 2025-02-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_userprofile_created_at_userprofile_last_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="location",
            field=models.CharField(default="Mehsana", max_length=255),
        ),
    ]
