# Generated by Django 4.2.16 on 2025-02-27 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_alter_complaint_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="google_drive_url",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="location",
            field=models.CharField(default="Mehsana", max_length=100),
        ),
        migrations.CreateModel(
            name="UserAttemptedLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coordinates", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempted_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
