# Generated by Django 4.2.16 on 2025-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_remove_complaint_google_drive_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="location",
            field=models.CharField(default="Mehsana", max_length=255),
        ),
    ]
