# Generated by Django 4.2.16 on 2025-02-27 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_alter_complaint_location"),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ComplaintReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(
                    on_delete=models.CASCADE,
                    to='myapp.Complaint',
                    to_field='complaint_id',  # Reference complaint_id string
                    db_column='complaint_id'  # Column name in DB
                )),
                ('user', models.ForeignKey(on_delete=models.CASCADE, to='myapp.CustomUser')),
            ],
            options={
                'unique_together': {('user', 'complaint')},
            },
        ),
    ]
