# Generated by Django 4.2.16 on 2025-02-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_complaint_counter_complaintreport"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="complaint",
            unique_together={("coordinates", "issue_type")},
        ),
    ]
