# Generated by Django 4.2.16 on 2025-03-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
    ]
